[package]
name = "msp432-svd2rust"
version = "0.1.0"
authors = ["Pramode <mail@pramode.in>"]

[dependencies]
msp432p401r = "0.1.2"
cortex-m = "0.3.0"

[dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.3"

[profile.release]
debug = true
lto = true
